//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceReports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class report01thas01Entities : DbContext
    {
        public report01thas01Entities()
            : base("name=report01thas01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StockLocation> StockLocations { get; set; }
    
        public virtual ObjectResult<THAS_CONNECT_StockValuationReport_Result> THAS_CONNECT_StockValuationReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_StockValuationReport_Result>("THAS_CONNECT_StockValuationReport");
        }
    
        public virtual ObjectResult<THAS_CONNECT_FinanceQuarantineBatches_Result> THAS_CONNECT_FinanceQuarantineBatches()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_FinanceQuarantineBatches_Result>("THAS_CONNECT_FinanceQuarantineBatches");
        }
    }
}
