//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocation
    {
        public string LocationCode { get; set; }
        public int LocationID { get; set; }
        public string Location { get; set; }
        public int ItemsInLocation { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool DefaultLocation { get; set; }
        public bool Quarantined { get; set; }
        public bool ExcludeMRP { get; set; }
        public bool Flowline { get; set; }
        public bool ExcludeAssignments { get; set; }
        public string Address { get; set; }
    }
}
